--DROP TABLE MEMBER;
--DROP SEQUENCE SEQ_UNO;

/* 
1. SYSTEM 계정에 접속한 상태에서 계정 생성 및 권한부여 쿼리문 작성
    CREATE USER [ID] IDENTIFIED BY [PW]; => 생성할 계정 ID, PW를 만들기
    GRANT RESOURCE, CONNECT TO [존재하는 계정 ID] => CRUD를 할 수 있는 권한 부여
*/
--CREATE USER KHJ IDENTIFIED BY KHJ;
--GRANT RESOURCE, CONNECT TO KHJ;

CREATE TABLE MEMBER (
    NO NUMBER PRIMARY KEY,
    ID VARCHAR2(30) NOT NULL UNIQUE,
    PASSWORD VARCHAR2(100) NOT NULL,
    NICKNAME VARCHAR2(30) NOT NULL UNIQUE,
    ENROLL_DATE DATE DEFAULT SYSDATE,
    STATUS VARCHAR2(1) DEFAULT 'Y' CHECK(STATUS IN('Y', 'N'))
);

COMMENT ON COLUMN MEMBER.NO IS '회원번호';
COMMENT ON COLUMN MEMBER.ID IS '아이디';
COMMENT ON COLUMN MEMBER.PASSWORD IS '비밀번호';
COMMENT ON COLUMN MEMBER.NICKNAME IS '닉네임';
COMMENT ON COLUMN MEMBER.ENROLL_DATE IS '회원가입일';
COMMENT ON COLUMN MEMBER.STATUS IS '회원활성화';

CREATE SEQUENCE SEQ_UNO;







